security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        login:
            entity:
                class: App\Entity\Usuario
                property: nick
    encoders:
        App\Entity\Usuario:
            algorithm: bcrypt
            cost: 13
    firewalls:
        main:
            anonymous: true
            provider: login
            form_login:
                login_path: index
                check_path: index
                default_target_path: main
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    access_control:
    - { path: ^/main, roles: ROLE_USER }
    # - { path: ^/zonaAdmin, roles: ROLE_ADMIN }
